version: "3.9"
services:
  api:
    build: .
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - "${API_PORT:-8000}:8000"
